### ISSUE TITLE
[GT-N7100/Android 4.4.2/Rooted] "/(inaccessable)"

### ISSUE THREAD

**Issue by Rbagman** [ScreamingHawk/android-slideshow#22]
F-Droid finally updated Slideshow (1.1.5) extSdCard and UsbDrive work great. Thanks.

FYI, I hit the back button while in /storage I get /(inaccessable); getting back requires flipping root off, exiting setting, entering setting, and flipping root on again.

**Comment by ScreamingHawk** [comment]
(inaccessible) appears when the application does not have read access on the folder. I not sure what allows and disallows read access in the root folder when the device is rooted. If you have any idea how I should get around this please let me know or submit a pull request if you can fix it yourself. (Do you think it is a real problem? Do you need to navigate that deep to get to your images directory?) 

The issue with navigation requiring flipping the settings is fixed as of 1.2.0. Might have to wait for another F-Droid update... Otherwise you can always build from source. If you need instructions for this create another ticket and I'll add something to the README. 

Hope that helps

**Comment by Rbagman** [comment]
No, I have no clue. I also have XDA Framework installed.

I hit the back button a few times too many coming off UsbDriveA. I expected it to stop in the / folder. I only mentioned it because it wasn't normal behavior.

Matter's closed for me.

**Comment by ScreamingHawk** [comment]
Thanks @Rbagman, I appreciate the update. Hopefully the 1.2.0 update fixes the 'stuck' navigation issue for you
