### ISSUE TITLE
Play sub-folders

### ISSUE THREAD

**Issue by howeyc** [ScreamingHawk/android-slideshow#36]
Is there a way to play sub-folders as well. All the way down the tree?

Also, let's say I'm at a level where I don't have any images in that folder, but I do in the sub-folders and want to play all images contained in all folders. Maybe a little "Play" icon in the lower right, like how G-Mail has the "+" icon down there to go to compose view?

**Comment by ScreamingHawk** [comment]
I really like this idea. 

Will push something through to the beta stream on the play store later tonight.

**Comment by ScreamingHawk** [comment]
Got excited and push it out already. You can [sign up for the beta here](https://play.google.com/apps/testing/link.standen.michael.slideshow) if you want to see the proposed implementation. 

The problem is that there is a huge up front calculation to get all the images in all subfolders. This is going to have a huge performance hit for users that use this feature on top level folders. 
I don't have an immediately obvious solution to this problem. 

Clicking an image in a folder will not navigate through subfolders. 

Before I roll this out to stable I want to have the following:

- [ ] Performance handling
- [ ] Configuration option to use sub folders or not (I can see new users using this button exclusively, instead of clicking an image)
- [ ] Translations (at least partial language support)

**Comment by howeyc** [comment]
This looks great! Thanks for looking into it!

I'm and F-Droid user, so I guess I'll wait. ;)

**Comment by howeyc** [comment]
I appreciate you doing this. I tried it out and it's great!

**Comment by ScreamingHawk** [comment]
@howeyc No problem. I'm genuinely happy to have it. I use this feature almost exclusively now.
